### ISSUE TITLE
OMCEdit not included?

### ISSUE THREAD

**Issue by loshlee** [abra-code/OMC#12]
The info page for OMCEdit (http://www.abracode.com/free/cmworkshop/omcedit.html) states that it is included with the OMC download. Where is it?

**Comment by FlashSheridan** [comment]
> Where is it?

Link in my Pull Request https://github.com/abra-code/OMC/pull/9, at least as of when I wrote it…

**Comment by loshlee** [comment]
It indicates that OMCEdit is included with the OMC download, but it isn't.
